enum NumericDataType::Type {
    Boolean,
    Short, Unsigned_Short,
    Int, Unsigned,
    LongLong, Unsigned_LongLong,
    Float, Double
}
class NumericDataType<<final>> {
    {static} + getInstance(cast : NumericDataType::Type)
}